### ISSUE TITLE
Keeps crashing after a day

### ISSUE THREAD

**Issue by bartdesign** [holgerpieta/Toshiba-AC-mqtt#3]
Hi, I have another issue. When i run this for a day or so it tends to crash. The response is the following:

```
Dec 04 12:22:28 homekit python3[1633835]: 2022-12-04 12:22:28,276:ERROR:toshiba_ac.device_manager: Something failed while connecting: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://mobileapi.toshibahomeaccontrols.com/api/Consumer/Registe>
Dec 04 12:22:28 homekit python3[1633835]: Traceback (most recent call last):
Dec 04 12:22:28 homekit python3[1633835]:   File "/home/bart/Toshiba-AC-mqtt/toshiba_ac/device_manager.py", line 55, in connect
Dec 04 12:22:28 homekit python3[1633835]:     self.sas_token = await self.http_api.register_client(self.device_id)
Dec 04 12:22:28 homekit python3[1633835]:   File "/home/bart/Toshiba-AC-mqtt/toshiba_ac/http_api.py", line 227, in register_client
Dec 04 12:22:28 homekit python3[1633835]:     res = await self.request_api(self.REGISTER_PATH, post=post)
Dec 04 12:22:28 homekit python3[1633835]:   File "/home/bart/Toshiba-AC-mqtt/toshiba_ac/http_api.py", line 86, in request_api
Dec 04 12:22:28 homekit python3[1633835]:     json = await response.json()
Dec 04 12:22:28 homekit python3[1633835]:   File "/home/bart/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1104, in json
Dec 04 12:22:28 homekit python3[1633835]:     raise ContentTypeError(
Dec 04 12:22:28 homekit python3[1633835]: aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://mobileapi.toshibahomeaccontrols.com/api/Consumer/RegisterMobileDevice')
Dec 04 12:22:28 homekit python3[1633835]: 2022-12-04 12:22:28,283:WARNING:toshiba_ac.device_manager: Shutting down 
```

It seems the RegisterMobileDevice function returns HTML but it tries to parse it as JSON. Any idea's how to fix this? 

Also when it crashed, it says Shutting down. But the python program itself does not exit or quit and keeps hanging until i restart it manually. I made this into a Ubuntu systemctl service; when it quits gracefully it will auto restart. But right now it just hangs on Shutting down and stays active.

**Comment by holgerpieta** [comment]
Sorry, had to edit your comment to make it readable.

I've tried to gracefully shut down the program when something fails, but I've already noticed that this not always works, especially when the program is still starting up.

I'm kind of confused that this error happens after a day or so and not immediately at startup. Are you sure it's not crashing for some other reasons, is restarted by the service and then crashes again on startup?

It looks like the system starts up, something fails, it tries to shut down, but some shutdown function never returns after being called.
I've added a new branch 'debug_shutdown', which adds some more debug output to see where it hangs.
Would you be able to try that?

**Comment by bartdesign** [comment]
Hi, i was unable to test this further. But to my surprise it is working fine for a few weeks now. So we can consider this resolved. Thank you for your support.
